### ISSUE TITLE
Seems to be incompatible with Xcode 7.3

### ISSUE THREAD

**Issue by kevinjbastien** [fortinmike/irradiated-xcode-theme#1]

**Comment by fortinmike** [comment]
I'm using it in Xcode 7.3 as we speak. Are you sure you installed the theme properly?

**Comment by kbastien** [comment]
I downloaded through Alcatraz, and then restarted Xcode.

On Thu, Mar 24, 2016 at 11:13 AM, Michaël Fortin <notifications@github.com>
wrote:

> I'm using it in Xcode 7.3 as we speak. Are you sure you installed the
> theme properly?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/fortinmike/irradiated-xcode-theme/issues/1#issuecomment-200954939>
>



-- 
Kevin Bastien
kevinbastien.com
m: (360)621-1649

**Comment by fortinmike** [comment]
I just tried deleting it from my machine and reinstalling with Alcatraz. Works for me. Don't forget to choose the theme in the "Fonts & Colors" section of Xcode's preferences! It's not applied automatically.

**Comment by kbastien** [comment]
Weird. I redownloaded alcatraz, and now it works for me. Thanks for being
patient!

On Fri, Mar 25, 2016 at 5:55 AM, Michaël Fortin <notifications@github.com>
wrote:

> I just tried deleting it from my machine and reinstalling with Alcatraz.
> Works for me. Don't forget to choose the theme in the "Fonts & Colors"
> section of Xcode's preferences! It's not applied automatically.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/fortinmike/irradiated-xcode-theme/issues/1#issuecomment-201268181>
>



-- 
Kevin Bastien
kevinbastien.com
m: (360)621-1649

**Comment by fortinmike** [comment]
No problem! I'm glad you got it working.
